spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/.h2/pde/n1/m7/db;
    username: sa
    password:
    platform: h2
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /console
